services:
  gitea:
    image: gitea/gitea:latest
    container_name: riff-gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:3000" 
      - "2222:22"

  jenkins:
    build: 
      context: ./ci
      dockerfile: Dockerfile
    container_name: riff-jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root 

volumes:
  gitea_data:
  jenkins_home:
